#cloud-config
repo_update: true
repo_upgrade: all
hostname: openvpn-server
timezone: "America/Sao_Paulo"

packages:
 - openvpn
 - easy-rsa

runcmd:
 # Initializing OpenVPN CA Configuration 
 - [ mkdir, /home/ubuntu/easy-rsa ]
 - [ sh, -c, "echo export EASYRSA_VARS_FILE='/usr/share/easy-rsa/vars' >> /etc/profile"] 
 - [ sh, -c, "cd /usr/share/easy-rsa && ./easyrsa init-pki" ]
 - [ sh, -c, 'echo set_var EASYRSA_DN "cn_only" > /home/ubuntu/easy-rsa/ca-config' ]
 - [ sh, -c, 'echo set_var EASYRSA_BATCH "1" >> /home/ubuntu/easy-rsa/ca-config' ]
 - [ sh, -c, 'echo set_var EASYRSA_REQ_CN "OpenVPN-CA" >> /home/ubuntu/easy-rsa/ca-config' ] 
 - [ sh, -c, 'echo set_var EASYRSA_ALGO "ec" >> /home/ubuntu/easy-rsa/ca-config' ]
 - [ sh, -c, 'echo set_var EASYRSA_DIGEST "sha512" >> /home/ubuntu/easy-rsa/ca-config' ]
 - [ sh, -c, 'cp /home/ubuntu/easy-rsa/ca-config /usr/share/easy-rsa/vars' ]
 - [ sh, -c, "cd /usr/share/easy-rsa && ./easyrsa build-ca nopass" ]

 # Initializing OpenVPN Server Certificate
 - [ sh, -c, 'echo set_var EASYRSA_DN "cn_only" > /home/ubuntu/easy-rsa/server-config' ]
 - [ sh, -c, 'echo set_var EASYRSA_BATCH "1" >> /home/ubuntu/easy-rsa/server-config' ]
 - [ sh, -c, 'echo set_var EASYRSA_REQ_CN "server" >> /home/ubuntu/easy-rsa/server-config' ] 
 - [ sh, -c, 'echo set_var EASYRSA_ALGO "ec" >> /home/ubuntu/easy-rsa/server-config' ]
 - [ sh, -c, 'echo set_var EASYRSA_DIGEST "sha512" >> /home/ubuntu/easy-rsa/server-config' ]
 - [ sh, -c, 'cp /home/ubuntu/easy-rsa/server-config /usr/share/easy-rsa/vars' ]
 - [ sh, -c, "cd /usr/share/easy-rsa && ./easyrsa gen-req server nopass" ]
 - [ sh, -c, "cd /usr/share/easy-rsa && ./easyrsa sign-req server server" ]

 - [ sh, -c, 'cp /usr/share/easy-rsa/pki/private/server.key /etc/openvpn/server/' ]
 - [ sh, -c, 'cp /usr/share/easy-rsa/pki/issued/server.crt /etc/openvpn/server/' ]
 - [ sh, -c, 'cp /usr/share/easy-rsa/pki/ca.crt /etc/openvpn/server/' ]
 
 # OpenVPN Cryptographic Configuration
 - [ sh, -c, "cd /usr/share/easy-rsa && openvpn --genkey --secret ta.key" ]
 - [ sh, -c, 'cp /usr/share/easy-rsa/ta.key /etc/openvpn/server/' ]

 # Setting default vars file
 - [ sh, -c, 'echo set_var EASYRSA_ALGO "ec" > /usr/share/easy-rsa/vars' ]
 - [ sh, -c, 'echo set_var EASYRSA_DIGEST "sha512" >> /usr/share/easy-rsa/vars' ]

 # OpenVPN Server Configuration
 - [ sh, -c, 'cp /usr/share/doc/openvpn/examples/sample-config-files/server.conf /etc/openvpn/server/' ]
 - [ sh, -c, "sed -i.bak 's/tls-auth ta.key 0/tls-crypt ta.key/g' /etc/openvpn/server/server.conf" ]
 - [ sh, -c, "sed -i.bak 's/cipher AES-256-CBC/cipher AES-256-GCM/g' /etc/openvpn/server/server.conf" ] 
 - [ sh, -c, "sed -i.bak 's/dh dh2048.pem/dh none/g' /etc/openvpn/server/server.conf" ]
 - [ sh, -c, 'echo " " >> /etc/openvpn/server/server.conf' ]
 - [ sh, -c, 'echo "auth SHA256" >> /etc/openvpn/server/server.conf' ] 
 - [ sh, -c, 'echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf' ]
 - [ sh, -c, 'sysctl -p' ]

 # Firewall Configuration
 - [ sh, -c, "sed -i.bak 's/DEFAULT_FORWARD_POLICY=\"DROP\"/DEFAULT_FORWARD_POLICY=\"ACCEPT\"/g' /etc/default/ufw" ]

 # Initializing OpenVPN
 - [ sh, -c, 'systemctl -f enable openvpn-server@server.service' ]
 - [ sh, -c, 'systemctl start openvpn-server@server.service' ]


bootcmd:
 - [sh, -c, 'ufw route allow in on eth0 out on eth0 from 10.8.0.0/8' ]
 - [sh, -c, 'ufw allow 1194/udp' ]
    

 



 #- systemctl start httpd
 #- sudo systemctl enable httpd
 #- [ sh, -c, "usermod -a -G apache ec2-user" ]
 #- [ sh, -c, "chown -R ec2-user:apache /var/www" ]
 #- chmod 2775 /var/www
 #- [ find, /var/www, -type, d, -exec, chmod, 2775, {}, \; ]
 #- [ find, /var/www, -type, f, -exec, chmod, 0664, {}, \; ]
 #- [ sh, -c, 'echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php' ]