---
- hosts: openvpn-server
  become: yes
  gather_facts: no

  tasks:
      
    - name: Add {{ subnet }} {{ mask }} to /etc/openvpn/server/server.conf
      lineinfile:
        path: /etc/openvpn/server/server.conf
        line: "push \"route {{ subnet }} {{ mask }}\""
        create: yes
        insertafter: EOF
        state: present

    - name: Restarting OpenVPN service
      ansible.builtin.systemd:
        name: openvpn-server@server.service
        state: restarted
        enabled: yes