---
- hosts: openvpn-server
  become: yes
  gather_facts: no
  
  tasks:

    - name: Revoke client certificate
      command: /usr/share/easy-rsa/easyrsa revoke {{ client_name }}
      args:
        chdir: /usr/share/easy-rsa
      register: revoke_client

    - name: Generate CRL
      command: /usr/share/easy-rsa/easyrsa gen-crl
      args:
        chdir: /usr/share/easy-rsa
      register: generate_crl

    - name: Copying CRL to OpenVPN server folder
      copy:
        src: /usr/share/easy-rsa/pki/crl.pem
        dest: /etc/openvpn/server/crl.pem
        remote_src: yes
      register: copy_crl

    - name: Removing commentary of CRL in OpenVPN server configuration
      lineinfile:
        path: /etc/openvpn/server/server.conf
        regexp: '^;crl-verify crl.pem'
        line: 'crl-verify crl.pem'
        state: present
      register: uncomment_crl

    - name: Restarting OpenVPN service
      ansible.builtin.systemd:
        name: openvpn-server@server.service
        state: restarted
        enabled: yes